### ISSUE TITLE
Support for nested components?

### ISSUE THREAD

**Issue by russelgal** [orenelbaum/babel-plugin-solid-undestructure#7]
```js
const Parent: Component=({...})=>{
    const Child: Component=({...})=>{...}
}
```

Child not working

**Comment by orenelbaum** [comment]
Yeah there's no support for nested components. I usually don't use them and I find this pattern a bit weird but I will definitely will consider it and probably add support when I have more time. Also feel free to make a PR if you feel like it.

**Comment by russelgal** [comment]
I have no idea how to do this (

**Comment by orenelbaum** [comment]
Is this still relevant to you? If so I'll work on it

**Comment by russelgal** [comment]
thank you in advance!

**Comment by orenelbaum** [comment]
Thank you for using the plugin!
Feature added with https://github.com/orenelbaum/babel-plugin-solid-undestructure/commit/d577bf3926c4c0d86c290efa6baf9f2d744e525a
